### ISSUE TITLE
Error executing show3d.py

### ISSUE THREAD

**Issue by uro1012** [ARTORG-IGT/cas-assignment#7]
When trying to execute the show3d.py script, I get the following errors.

> ERROR: In C:\VPP\standalone-build\VTK-source\Filters\Core\vtkSmoothPolyDataFilter.cxx, line 331
vtkSmoothPolyDataFilter (000000001318B990): No data to smooth!

> ERROR: In C:\VPP\standalone-build\VTK-source\Filters\Core\vtkSmoothPolyDataFilter.cxx, line 331
vtkSmoothPolyDataFilter (0000000013346320): No data to smooth!

> ERROR: In C:\VPP\standalone-build\VTK-source\Filters\Core\vtkSmoothPolyDataFilter.cxx, line 331
vtkSmoothPolyDataFilter (0000000013317620): No data to smooth!

I checked and the _C:\VPP_ repository does not exist on my computer. Am I missing some program needed to run the script, or is it some hard-coded path? A OpenGL window opens, but it stays black due to the error.

For information, I am working on a Windows Seven machine.

**Comment by ipa** [comment]
No the C:\VPP is just debug information from the person who built VTK for python. 

The important part is 
`vtkSmoothPolyDataFilter (0000000013317620): No data to smooth!`
This means that the script can't find the segmentation in the data.

Could you send me your `segmentation.npy` file? It should be generated after you press 's' in the segmentation window.

**Comment by uro1012** [comment]
The problem was just that I didn't save anything. Now everything works fine.
